// <auto-generated />
using System;
using CaeManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaeManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CaeManagerDbContext))]
    [Migration("20260718232056_AgregarLecturaIaYNotificaciones")]
    partial class AgregarLecturaIaYNotificaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CaeManager.Domain.Alertas.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaGeneracionUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("Alertas", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Asignaciones.Asignacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CentroId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaAlta")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaBaja")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrabajadorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("TrabajadorId", "CentroId", "FechaAlta")
                        .IsUnique();

                    b.ToTable("Asignaciones", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Auditoria.RegistroAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DatosAntes")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatosDespues")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadTipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FechaUtc");

                    b.HasIndex("EntidadTipo", "EntidadId");

                    b.ToTable("RegistrosAuditoria", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Centros.Centro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoCentro")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contacto")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ContratoVigenteHasta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EliminadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Centros", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Centros.PlataformaAcceso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CentroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contrasena")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombrePlataforma")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlAcceso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CentroId")
                        .IsUnique();

                    b.ToTable("PlataformasAcceso", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cif")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EjecutivoUsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EliminadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsCritico")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notas")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cif")
                        .IsUnique();

                    b.HasIndex("EjecutivoUsuarioId");

                    b.HasIndex("RazonSocial");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Configuracion.ParametroSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("UmbralAmbarDias")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UmbralRojoDias")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ParametrosSistema", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            UmbralAmbarDias = 30,
                            UmbralRojoDias = 15
                        });
                });

            modelBuilder.Entity("CaeManager.Domain.Documentos.ConfiguracionIaDocumentoCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "TipoDocumentoId")
                        .IsUnique();

                    b.ToTable("ConfiguracionesIaDocumentoCliente", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Documentos.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchivoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EliminadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TrabajadorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VehiculoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FechaVencimiento");

                    b.HasIndex("ClienteId", "TipoDocumentoId");

                    b.HasIndex("EmpresaId", "TipoDocumentoId");

                    b.HasIndex("TrabajadorId", "TipoDocumentoId");

                    b.HasIndex("VehiculoId", "TipoDocumentoId");

                    b.ToTable("Documentos", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Documentos.TipoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AmbitoAplicacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AplicaVencimientoAutomatico")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CriteriosValidacion")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsObligatorio")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LecturaIaActiva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeSolicitaA")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VigenciaMeses")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposDocumento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AmbitoAplicacion = "Trabajador",
                            AplicaVencimientoAutomatico = true,
                            EsObligatorio = false,
                            LecturaIaActiva = true,
                            Nombre = "Apto médico laboral",
                            Notas = "Renovación anual estándar.",
                            Orden = 1,
                            VigenciaMeses = 12
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AmbitoAplicacion = "Trabajador",
                            AplicaVencimientoAutomatico = true,
                            EsObligatorio = false,
                            LecturaIaActiva = true,
                            Nombre = "EPIS (firma)",
                            Notas = "Se firman cada año según nota de origen.",
                            Orden = 2,
                            VigenciaMeses = 12
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            AmbitoAplicacion = "Trabajador",
                            AplicaVencimientoAutomatico = true,
                            EsObligatorio = false,
                            LecturaIaActiva = true,
                            Nombre = "Reciclaje 4h",
                            Notas = "Cada 4 años, según Dpto. Formación.",
                            Orden = 3,
                            VigenciaMeses = 48
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            AmbitoAplicacion = "Trabajador",
                            AplicaVencimientoAutomatico = true,
                            EsObligatorio = false,
                            LecturaIaActiva = true,
                            Nombre = "Formación Art. 19",
                            Notas = "Recordatorio cada 3 años.",
                            Orden = 4,
                            VigenciaMeses = 36
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            AmbitoAplicacion = "Trabajador",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = false,
                            LecturaIaActiva = true,
                            Nombre = "Formación 60h (base convenio)",
                            Notas = "Formación base, no consta caducidad.",
                            Orden = 5
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            AmbitoAplicacion = "Trabajador",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = false,
                            LecturaIaActiva = true,
                            Nombre = "Formación 20h",
                            Notas = "Mismo curso de convenio que 60h/6h, no consta caducidad.",
                            Orden = 6
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            AmbitoAplicacion = "Trabajador",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = false,
                            LecturaIaActiva = true,
                            Nombre = "Formación 6h",
                            Notas = "Mismo curso de convenio que 60h/20h, no consta caducidad.",
                            Orden = 7
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            AmbitoAplicacion = "Trabajador",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = false,
                            LecturaIaActiva = true,
                            Nombre = "Información Art. 18",
                            Notas = "No consta periodicidad de renovación.",
                            Orden = 8
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            AmbitoAplicacion = "Trabajador",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = false,
                            LecturaIaActiva = true,
                            Nombre = "Carretillas elevadoras",
                            Notas = "Configurable si el convenio interno define vigencia.",
                            Orden = 9
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000a"),
                            AmbitoAplicacion = "Trabajador",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = false,
                            LecturaIaActiva = true,
                            Nombre = "PEMP (plataformas elevadoras)",
                            Notas = "Configurable si el convenio interno define vigencia.",
                            Orden = 10
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000b"),
                            AmbitoAplicacion = "Trabajador",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = false,
                            LecturaIaActiva = true,
                            Nombre = "LOTO (4h)",
                            Notas = "Configurable si el convenio interno define vigencia.",
                            Orden = 11
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000c"),
                            AmbitoAplicacion = "Trabajador",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = false,
                            LecturaIaActiva = true,
                            Nombre = "Seguridad alimentaria",
                            Notas = "Configurable si el convenio interno define vigencia.",
                            Orden = 12
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000d"),
                            AmbitoAplicacion = "Trabajador",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = false,
                            LecturaIaActiva = true,
                            Nombre = "Primeros auxilios",
                            Notas = "Se recomienda revisar cada 2 años; sin dato oficial de origen.",
                            Orden = 13
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000e"),
                            AmbitoAplicacion = "Trabajador",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = false,
                            LecturaIaActiva = true,
                            Nombre = "Espacios confinados",
                            Notas = "Configurable si el convenio interno define vigencia.",
                            Orden = 14
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000f"),
                            AmbitoAplicacion = "Trabajador",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = false,
                            LecturaIaActiva = true,
                            Nombre = "Trabajos en altura (8h)",
                            Notas = "Configurable si el convenio interno define vigencia.",
                            Orden = 15
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            AmbitoAplicacion = "Empresa",
                            AplicaVencimientoAutomatico = true,
                            EsObligatorio = true,
                            LecturaIaActiva = true,
                            Nombre = "Certificado de estar al corriente con la Seguridad Social",
                            Notas = "Mensual.",
                            Orden = 16,
                            VigenciaMeses = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            AmbitoAplicacion = "Empresa",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = true,
                            LecturaIaActiva = true,
                            Nombre = "Certificado de estar al corriente con Hacienda",
                            Notas = "Vigencia variable (1, 3, 6 o 12 meses según lo que exija el cliente) — la fecha de vencimiento se introduce a mano al subir el documento.",
                            Orden = 17
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            AmbitoAplicacion = "Empresa",
                            AplicaVencimientoAutomatico = true,
                            EsObligatorio = true,
                            LecturaIaActiva = true,
                            Nombre = "ITA",
                            Notas = "Mensual.",
                            Orden = 18,
                            VigenciaMeses = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            AmbitoAplicacion = "Empresa",
                            AplicaVencimientoAutomatico = true,
                            EsObligatorio = true,
                            LecturaIaActiva = true,
                            Nombre = "RLC/TC1",
                            Notas = "Mensual — el documento de un periodo (p. ej. 01/05) vence 3 meses después (01/08), porque tarda en emitirse con la fecha del periodo ya pasada.",
                            Orden = 19,
                            VigenciaMeses = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            AmbitoAplicacion = "Empresa",
                            AplicaVencimientoAutomatico = true,
                            EsObligatorio = true,
                            LecturaIaActiva = true,
                            Nombre = "Recibo de pago RLC/TC1",
                            Notas = "Mismo criterio de vigencia que el RLC/TC1.",
                            Orden = 20,
                            VigenciaMeses = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            AmbitoAplicacion = "Empresa",
                            AplicaVencimientoAutomatico = true,
                            EsObligatorio = true,
                            LecturaIaActiva = true,
                            Nombre = "RLC/TC1 + Recibo de pago",
                            Notas = "Variante combinada — mismo criterio de vigencia que el RLC/TC1.",
                            Orden = 21,
                            VigenciaMeses = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            AmbitoAplicacion = "Empresa",
                            AplicaVencimientoAutomatico = true,
                            EsObligatorio = true,
                            LecturaIaActiva = true,
                            Nombre = "RNT/TC2",
                            Notas = "Mismo criterio que el RLC/TC1.",
                            Orden = 22,
                            VigenciaMeses = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            AmbitoAplicacion = "Empresa",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = true,
                            LecturaIaActiva = true,
                            Nombre = "Mutua",
                            Notas = "Vigencia sin especificar — fecha de vencimiento manual.",
                            Orden = 23
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            AmbitoAplicacion = "Empresa",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = true,
                            LecturaIaActiva = true,
                            Nombre = "Seguro de Responsabilidad Civil + recibo de pago",
                            Notas = "Vigencia sin especificar — fecha de vencimiento manual.",
                            Orden = 24
                        },
                        new
                        {
                            Id = new Guid("2000000a-0000-0000-0000-00000000000a"),
                            AmbitoAplicacion = "Empresa",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = true,
                            LecturaIaActiva = true,
                            Nombre = "SPA (Servicio de Prevención Ajeno)",
                            Notas = "Debe venir acompañado de un certificado de pago que indica la fecha fin de validez — se introduce esa fecha manualmente.",
                            Orden = 25
                        },
                        new
                        {
                            Id = new Guid("2000000b-0000-0000-0000-00000000000b"),
                            AmbitoAplicacion = "Empresa",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = true,
                            LecturaIaActiva = true,
                            Nombre = "EVR (Evaluación de Riesgos Laborales)",
                            Notas = "Vigencia sin especificar — fecha de vencimiento manual.",
                            Orden = 26
                        },
                        new
                        {
                            Id = new Guid("2000000c-0000-0000-0000-00000000000c"),
                            AmbitoAplicacion = "Empresa",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = true,
                            LecturaIaActiva = true,
                            Nombre = "PAP (Planificación de la Actividad Preventiva)",
                            Notas = "Vigencia sin especificar — fecha de vencimiento manual.",
                            Orden = 27
                        },
                        new
                        {
                            Id = new Guid("2000000d-0000-0000-0000-00000000000d"),
                            AmbitoAplicacion = "Empresa",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = false,
                            LecturaIaActiva = true,
                            Nombre = "Tarjeta CIF",
                            Notas = "Opcional — no obligatorio para todos los clientes.",
                            Orden = 28
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            AmbitoAplicacion = "Vehiculo",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = true,
                            LecturaIaActiva = true,
                            Nombre = "ITC",
                            Notas = "Vigencia sin especificar — fecha de vencimiento manual.",
                            Orden = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            AmbitoAplicacion = "Vehiculo",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = true,
                            LecturaIaActiva = true,
                            Nombre = "Ficha técnica",
                            Notas = "No caduca por sí sola, pero se pide como documento adjunto del vehículo.",
                            Orden = 2
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            AmbitoAplicacion = "Vehiculo",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = true,
                            LecturaIaActiva = true,
                            Nombre = "Seguro",
                            Notas = "Vigencia sin especificar — fecha de vencimiento manual.",
                            Orden = 3
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            AmbitoAplicacion = "Vehiculo",
                            AplicaVencimientoAutomatico = false,
                            EsObligatorio = true,
                            LecturaIaActiva = true,
                            Nombre = "Autorización de circulación",
                            Notas = "Vigencia sin especificar — fecha de vencimiento manual.",
                            Orden = 4
                        });
                });

            modelBuilder.Entity("CaeManager.Domain.Documentos.TipoDocumentoCentro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CentroId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("TipoDocumentoId", "CentroId")
                        .IsUnique();

                    b.ToTable("TiposDocumentoCentros", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Empresas.CredencialAccesoEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CampoEmpresa")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contrasena")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlAcceso")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique();

                    b.ToTable("CredencialesAccesoEmpresa", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Empresas.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cif")
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EliminadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cif")
                        .IsUnique();

                    b.HasIndex("RazonSocial")
                        .IsUnique();

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Empresas.EmpresaCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpresaId", "ClienteId")
                        .IsUnique();

                    b.ToTable("EmpresasClientes", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Notificaciones.NotificacionUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadaEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Leida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextoAccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlAccion")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioDestinatarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioDestinatarioId", "Leida");

                    b.ToTable("NotificacionesUsuario", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.RequisitosDocumentales.RequisitoDocumental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("BloqueaAcceso")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CentroId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EliminadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodicidadEspecial")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.ToTable("RequisitosDocumentales", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Subcontratas.CredencialAccesoSubcontrata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CampoEmpresa")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contrasena")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubcontrataId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlAcceso")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubcontrataId")
                        .IsUnique();

                    b.ToTable("CredencialesAccesoSubcontrata", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Subcontratas.Subcontrata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EliminadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RazonSocial")
                        .IsUnique();

                    b.ToTable("Subcontratas", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Subcontratas.SubcontrataCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubcontrataId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("SubcontrataId", "ClienteId")
                        .IsUnique();

                    b.ToTable("SubcontratasClientes", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Subcontratas.SubcontrataEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubcontrataId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("SubcontrataId", "EmpresaId")
                        .IsUnique();

                    b.ToTable("SubcontratasEmpresas", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Trabajadores.Trabajador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EliminadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubcontrataId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.HasIndex("SubcontrataId");

                    b.ToTable("Trabajadores", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Vehiculos.Vehiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EliminadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroPlaca")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubcontrataId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("NumeroPlaca")
                        .IsUnique();

                    b.HasIndex("SubcontrataId");

                    b.ToTable("Vehiculos", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Visitas.Visita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CentroId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EliminadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificadoCliente")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("FechaFin");

                    b.ToTable("Visitas", (string)null);
                });

            modelBuilder.Entity("CaeManager.Domain.Visitas.VisitaTrabajador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrabajadorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VisitaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrabajadorId");

                    b.HasIndex("VisitaId");

                    b.HasIndex("VisitaId", "TrabajadorId")
                        .IsUnique();

                    b.ToTable("VisitasTrabajadores", (string)null);
                });

            modelBuilder.Entity("CaeManager.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CoordinadorUsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DebeCambiarContrasena")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tema")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            ConcurrencyStamp = "30000000-0000-0000-0000-000000000001",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            ConcurrencyStamp = "30000000-0000-0000-0000-000000000002",
                            Name = "CoordinadorCae",
                            NormalizedName = "COORDINADORCAE"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            ConcurrencyStamp = "30000000-0000-0000-0000-000000000003",
                            Name = "GestorCae",
                            NormalizedName = "GESTORCAE"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            ConcurrencyStamp = "30000000-0000-0000-0000-000000000004",
                            Name = "Consulta",
                            NormalizedName = "CONSULTA"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            ConcurrencyStamp = "30000000-0000-0000-0000-000000000005",
                            Name = "DireccionCae",
                            NormalizedName = "DIRECCIONCAE"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            ConcurrencyStamp = "30000000-0000-0000-0000-000000000006",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CaeManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CaeManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaeManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CaeManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
