// <auto-generated />
using CaeManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CaeManager.Migrations.PostgreSQL.Migrations
{
    [DbContext(typeof(CaeManagerDbContext))]
    [Migration("20260801120000_HabilitarRlsPostgres")]
    partial class HabilitarRlsPostgres
    {
        /// <inheritdoc />
        /// <remarks>
        /// Sin cuerpo a propósito: esta migración es SQL de servidor puro
        /// (RLS, roles, grants) y no toca el modelo de EF — ninguna entidad
        /// ni propiedad cambia, así que no hay nada nuevo que describir aquí
        /// respecto a CaeManagerDbContextModelSnapshot.cs (que sigue siendo
        /// la representación fiel del modelo actual, sin tocar). Este método
        /// no lo invoca Database.MigrateAsync() — solo herramental de diseño
        /// (dotnet ef migrations add/script con --target-migration) que este
        /// repositorio no usa hoy en este flujo.
        /// </remarks>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
