// <auto-generated />
using CaeManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CaeManager.Migrations.PostgreSQL.Migrations
{
    [DbContext(typeof(CaeManagerDbContext))]
    [Migration("20260801130000_AgregarTrabajosAnalisisDocumento")]
    partial class AgregarTrabajosAnalisisDocumento
    {
        /// <inheritdoc />
        /// <remarks>
        /// Sin cuerpo a propósito — ver la misma nota en
        /// HabilitarRlsPostgres.Designer.cs: Database.MigrateAsync() no lo
        /// invoca, y CaeManagerDbContextModelSnapshot.cs (el que sí usa
        /// `dotnet ef migrations has-pending-model-changes`) se actualiza en
        /// esta misma migración con el modelo real, completo.
        /// </remarks>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
