// <auto-generated />
using CaeManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CaeManager.Migrations.PostgreSQL.Migrations
{
    [DbContext(typeof(CaeManagerDbContext))]
    [Migration("20260925024247_AuditoriaSoloInsercionParaRuntime")]
    partial class AuditoriaSoloInsercionParaRuntime
    {
        /// <inheritdoc />
        /// <remarks>
        /// Sin cuerpo a propósito, como <c>HabilitarRlsPostgres</c>: SQL de
        /// servidor puro (un REVOKE), sin cambio en el modelo de EF.
        /// </remarks>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
